AWSTemplateFormatVersion: 2010-09-09
Resources: 
  DevEC2Instance: 
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: ami-05d72852800cbf29e
      InstanceType: t2.small
      KeyName: cfn-key-2
